services:
  xypad:
    image: xypad:v5
    container_name: XYPad
    restart: unless-stopped
    ports:
      - "9090:9000" # 管理后台端口
    volumes:
      - xypad:/app
      - redis_data:/var/lib/redis

volumes:
  redis_data:
    name: redis_data
  xypad:
    name: XYPad
